#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(git rev-parse --show-toplevel)"
cd "$ROOT_DIR"

./scripts/test-all.sh
./scripts/test-ui.sh
./scripts/test-selenium-webdriver.sh
./scripts/test-cucumber.sh
